name: 'Apps: Release Please'

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please Action
        uses: googleapis/release-please-action@v4
        with:
          target-branch: main